name: CI

on: push

env:
  FILE_PATH_BOILERPLATE_APP_VERSION_INFO_CI: ./apps/boilerplate-app/src/common/version/VersionInfoCI.ts

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Setup Node.js âš™ï¸ - Cache dependencies âš¡ - Install dependencies ğŸ”§
        uses: ./.github/workflows/actions/setup_node-cache_dep-install_dep

      - name: Version Info ğŸ’‰
        run: |
          echo "write version, branch & commit id to $FILE_PATH_BOILERPLATE_APP_VERSION_INFO_CI"
          echo "export const VersionInfoCI = { tag: ''$GITHUB_REF_NAME'', branch: ''$CI_COMMIT_REF_NAME'', commit: ''$CI_COMMIT_SHA'' }" > $FILE_PATH_BOILERPLATE_APP_VERSION_INFO_CI
          cat $FILE_PATH_BOILERPLATE_APP_VERSION_INFO_CI

      - name: Build ğŸ—ï¸
        run: npm run build

      - name: Lint âœ…
        run: npm run lint

      - name: tsc ğŸ”
        run: npm run tsc

      - name: Test ğŸ§ª
        run: npm run test

      - name: Deploy ğŸš€
        run: npm run lint
