name: CI

on: push

env:
  FILE_PATH_BOILERPLATE_APP_VERSION_INFO: ./apps/boilerplate-app/src/common/version/VersionInfo.ts

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Setup Node.js âš™ï¸ - Cache dependencies âš¡ - Install dependencies ğŸ”§
        uses: ./.github/workflows/actions/setup_node-cache_dep-install_dep

      - name: Branch name
        id: branch_name
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

      - name: Build base image
        run: |
          echo $SOURCE_NAME
          echo $SOURCE_BRANCH
          echo $SOURCE_TAG
        env:
          SOURCE_NAME: ${{ steps.branch_name.outputs.SOURCE_NAME }}
          SOURCE_BRANCH: ${{ steps.branch_name.outputs.SOURCE_BRANCH }}
          SOURCE_TAG: ${{ steps.branch_name.outputs.SOURCE_TAG }}

      - name: Version Info ğŸ’‰
        run: |
          echo "value: ${GITHUB_REF/refs\/tags\//}"
          echo "write version, branch & commit id to $FILE_PATH_BOILERPLATE_APP_VERSION_INFO"
          echo "export const VersionInfo = { tag: '$GITHUB_REF_NAME', branch: '$GITHUB_REF_NAME', commit: '$GITHUB_SHA' };" > $FILE_PATH_BOILERPLATE_APP_VERSION_INFO
          cat $FILE_PATH_BOILERPLATE_APP_VERSION_INFO

      - name: Build ğŸ—ï¸
        run: npm run build

      - name: Lint âœ…
        run: npm run lint

      - name: tsc ğŸ”
        run: npm run tsc

      - name: Test ğŸ§ª
        run: npm run test

      - name: Deploy ğŸš€
        run: npm run lint
