name: CI

on: push

env:
  FILE_PATH_BOILERPLATE_APP_VERSION_INFO: ./apps/boilerplate-app/src/common/version/VersionInfo.ts
  FILE_PATH_BOILERPLATE_APP_BUILD_NEXT: ./apps/boilerplate-app/build-next-static

  FILE_PATH_BOILERPLATE_WEBSITE_VERSION_INFO: ./apps/boilerplate-website/src/common/version/VersionInfo.ts
  FILE_PATH_BOILERPLATE_WEBSITE_BUILD_NEXT: ./apps/boilerplate-website/build-next-static

  CACHE_KEY_BUILD: build_app_next-${{ github.github_sha }}

jobs:
  build:
    name: Build ğŸ—ï¸
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Setup Node.js âš™ï¸ - Cache dependencies âš¡ - Install dependencies ğŸ”§
        uses: ./.github/workflows/actions/setup_node-cache_dep-install_dep

      - name: Version Info ğŸ’‰
        run: |
          COMMIT=$GITHUB_SHA
          BRANCH=${GITHUB_REF#refs/heads/}
          TAG=''
          if [[ ${{ github.ref_type }} == 'tag' ]]; then
            TAG=${GITHUB_REF#refs/tags/}
          fi
          echo "write tag, branch & commit id to $FILE_PATH_BOILERPLATE_APP_VERSION_INFO"
          echo "export const VersionInfo = { tag: '$TAG', branch: '$BRANCH', commit: '$COMMIT' };" > $FILE_PATH_BOILERPLATE_APP_VERSION_INFO
          cat $FILE_PATH_BOILERPLATE_APP_VERSION_INFO

      - name: Build ğŸ—ï¸
        run: npm run build

      - name: Cache build âš¡
        id: cache_build
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.FILE_PATH_BOILERPLATE_APP_BUILD_NEXT }}
            ${{ env.FILE_PATH_BOILERPLATE_WEBSITE_BUILD_NEXT }}
          key: build_app_next-${{ github.ref_type }}

  # lint:
  #   name: Lint âœ…
  #   needs: build
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout ğŸ›ï¸
  #       uses: actions/checkout@v3

  #     - name: Setup Node.js âš™ï¸ - Cache dependencies âš¡ - Install dependencies ğŸ”§
  #       uses: ./.github/workflows/actions/setup_node-cache_dep-install_dep

  #     - name: Lint âœ…
  #       run: npm run lint

  # tsc:
  #   name: tsc ğŸ”
  #   needs: build
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout ğŸ›ï¸
  #       uses: actions/checkout@v3

  #     - name: Setup Node.js âš™ï¸ - Cache dependencies âš¡ - Install dependencies ğŸ”§
  #       uses: ./.github/workflows/actions/setup_node-cache_dep-install_dep

  #     - name: tsc ğŸ”
  #       run: npm run tsc

  # test:
  #   name: Test ğŸ§ª
  #   needs: build
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout ğŸ›ï¸
  #       uses: actions/checkout@v3

  #     - name: Setup Node.js âš™ï¸ - Cache dependencies âš¡ - Install dependencies ğŸ”§
  #       uses: ./.github/workflows/actions/setup_node-cache_dep-install_dep

  #     - name: Test ğŸ§ª
  #       run: npm run test

  deploy-app-stage:
    name: Deploy App Stage ğŸš€
    # needs: [build, lint, tsc, test]
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    environment:
      name: App Stage
      url: https://turbo-app-stage.netlify.app

    steps:
      - uses: actions/cache@v3
        with:
          path: ${{ env.FILE_PATH_BOILERPLATE_APP_BUILD_NEXT }}
          key: build_app_next-${{ github.ref_type }}

      - uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: ${{ env.FILE_PATH_BOILERPLATE_APP_BUILD_NEXT }}
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_STAGE_BOILERPLATE_APP }}

  deploy-app-prod:
    name: Deploy App Production ğŸš€
    # needs: [build, lint, tsc, test]
    needs: build
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'

    environment:
      name: App Prod
      url: https://turbo-app-prod.netlify.app/

    steps:
      - uses: actions/cache@v3
        with:
          path: ${{ env.FILE_PATH_BOILERPLATE_APP_BUILD_NEXT }}
          key: build_app_next-${{ github.ref_type }}

      - uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: ${{ env.FILE_PATH_BOILERPLATE_APP_BUILD_NEXT }}
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_PROD_BOILERPLATE_APP }}
