name: CI

on: push

env:
  FILE_PATH_BOILERPLATE_APP_VERSION_INFO: ./apps/boilerplate-app/src/common/version/VersionInfo.ts

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v3

      - name: Setup Node.js âš™ï¸ - Cache dependencies âš¡ - Install dependencies ðŸ”§
        uses: ./.github/workflows/actions/setup_node-cache_dep-install_dep

      - name: Version Info ðŸ’‰
        id: version_info
        run: |
          echo ::set-output name=COMMIT::$GITHUB_SHA
          echo ::set-output name=BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}

      # - name: Build ðŸ—ï¸
      #   run: npm run build

      # - name: Lint âœ…
      #   run: npm run lint

      # - name: tsc ðŸ”Ž
      #   run: npm run tsc

      # - name: Test ðŸ§ª
      #   run: npm run test

      - name: Deploy Stage ðŸš€
        if: github.ref == 'refs/heads/main'
        env:
          COMMIT: ${{ steps.version_info.outputs.COMMIT }}
          BRANCH: ${{ steps.version_info.outputs.BRANCH }}
          TAG: ${{ steps.version_info.outputs.TAG }}
        run: |
          echo "write version, branch & commit id to $FILE_PATH_BOILERPLATE_APP_VERSION_INFO"
          echo "export const VersionInfo = { tag: '', branch: '$BRANCH', commit: '$COMMIT' };" > $FILE_PATH_BOILERPLATE_APP_VERSION_INFO
          cat $FILE_PATH_BOILERPLATE_APP_VERSION_INFO

      - name: Deploy Production ðŸš€
        if: github.ref_type == 'tags' && contains(github.ref_name, 'main')
        env:
          COMMIT: ${{ steps.version_info.outputs.COMMIT }}
          BRANCH: ${{ steps.version_info.outputs.BRANCH }}
          TAG: ${{ steps.version_info.outputs.TAG }}
        run: |
          echo "write version, branch & commit id to $FILE_PATH_BOILERPLATE_APP_VERSION_INFO"
          echo "export const VersionInfo = { tag: '$TAG', branch: '$BRANCH', commit: '$COMMIT' };" > $FILE_PATH_BOILERPLATE_APP_VERSION_INFO
          cat $FILE_PATH_BOILERPLATE_APP_VERSION_INFO
