name: CI

on: push

env:
  FILE_PATH_BOILERPLATE_APP_VERSION_INFO: ./apps/boilerplate-app/src/common/version/VersionInfo.ts # move to single package
  FILE_PATH_BOILERPLATE_APP_BUILD_NEXT: './apps/boilerplate-app/build-next-static'

  FILE_PATH_BOILERPLATE_WEBSITE_VERSION_INFO: ./apps/boilerplate-website/src/common/version/VersionInfo.ts
  FILE_PATH_BOILERPLATE_WEBSITE_BUILD_NEXT: './apps/boilerplate-website/build-next-static'

  FILE_PATH_UI_VERSION_INFO: ./packages/ui/version/VersionInfo.ts
  FILE_PATH_UI_BUILD: './packages/ui/dist'

  CACHE_KEY_BUILD: build-${{ github.sha }}

jobs:
  build:
    name: Build üèóÔ∏è
    runs-on: ubuntu-latest

    steps:
      - name: Checkout üõéÔ∏è
        uses: actions/checkout@v3

      - name: Setup Node.js ‚öôÔ∏è - Cache dependencies ‚ö° - Install dependencies üîß
        uses: ./.github/workflows/actions/setup_node-cache_dep-install_dep

      - name: Version Info üíâ
        run: |
          COMMIT=$GITHUB_SHA
          BRANCH=${GITHUB_REF#refs/heads/}
          TAG=''
          if [[ ${{ github.ref_type }} == 'tag' ]]; then
            TAG=${GITHUB_REF#refs/tags/}
          fi
          echo "write tag, branch & commit id to $FILE_PATH_BOILERPLATE_APP_VERSION_INFO"
          echo "export const VersionInfo = { tag: '$TAG', branch: '$BRANCH', commit: '$COMMIT' };" > $FILE_PATH_BOILERPLATE_APP_VERSION_INFO
          cat $FILE_PATH_BOILERPLATE_APP_VERSION_INFO

      - name: Build üèóÔ∏è
        run: npm run build

      - name: Cache build ‚ö°
        id: cache_build
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.FILE_PATH_BOILERPLATE_APP_BUILD_NEXT }}
            ${{ env.FILE_PATH_BOILERPLATE_WEBSITE_BUILD_NEXT }}
            ${{ env.FILE_PATH_UI_BUILD }}
          key: ${{ env.CACHE_KEY_BUILD }}

  # lint:
  #   name: Lint ‚úÖ
  #   needs: build
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout üõéÔ∏è
  #       uses: actions/checkout@v3

  #     - name: Setup Node.js ‚öôÔ∏è - Cache dependencies ‚ö° - Install dependencies üîß
  #       uses: ./.github/workflows/actions/setup_node-cache_dep-install_dep

  #     - name: Lint ‚úÖ
  #       run: npm run lint

  # tsc:
  #   name: tsc üîé
  #   needs: build
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout üõéÔ∏è
  #       uses: actions/checkout@v3

  #     - name: Setup Node.js ‚öôÔ∏è - Cache dependencies ‚ö° - Install dependencies üîß
  #       uses: ./.github/workflows/actions/setup_node-cache_dep-install_dep

  #     - name: tsc üîé
  #       run: npm run tsc

  # test:
  #   name: Test üß™
  #   needs: build
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout üõéÔ∏è
  #       uses: actions/checkout@v3

  #     - name: Setup Node.js ‚öôÔ∏è - Cache dependencies ‚ö° - Install dependencies üîß
  #       uses: ./.github/workflows/actions/setup_node-cache_dep-install_dep

  #     - name: Test üß™
  #       run: npm run test

  deploy-app-stage:
    name: Deploy App Stage üöÄ
    # needs: [build, lint, tsc, test]
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    environment:
      name: App Stage
      url: https://turbo-app-stage.netlify.app

    steps:
      - uses: actions/cache@v3
        with:
          path: |
            ${{ env.FILE_PATH_BOILERPLATE_APP_BUILD_NEXT }}
            ${{ env.FILE_PATH_BOILERPLATE_WEBSITE_BUILD_NEXT }}
            ${{ env.FILE_PATH_UI_BUILD }}
          key: ${{ env.CACHE_KEY_BUILD }}

      - uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: ${{ env.FILE_PATH_BOILERPLATE_APP_BUILD_NEXT }}
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_STAGE_BOILERPLATE_APP }}

  deploy-app-prod:
    name: Deploy App Production üöÄ
    # needs: [build, lint, tsc, test]
    needs: build
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'

    environment:
      name: App Prod
      url: https://turbo-app-prod.netlify.app/

    steps:
      - uses: actions/cache@v3
        with:
          path: |
            ${{ env.FILE_PATH_BOILERPLATE_APP_BUILD_NEXT }}
            ${{ env.FILE_PATH_BOILERPLATE_WEBSITE_BUILD_NEXT }}
            ${{ env.FILE_PATH_UI_BUILD }}
          key: ${{ env.CACHE_KEY_BUILD }}

      - uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: ${{ env.FILE_PATH_BOILERPLATE_APP_BUILD_NEXT }}
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_PROD_BOILERPLATE_APP }}

  deploy-ui-stage:
    name: Deploy UI Stage üöÄ
    # needs: [build, lint, tsc, test]
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    environment:
      name: UI Stage
      url: https://turbo-ui-stage.netlify.app

    steps:
      - uses: actions/cache@v3
        with:
          path: |
            ${{ env.FILE_PATH_BOILERPLATE_APP_BUILD_NEXT }}
            ${{ env.FILE_PATH_BOILERPLATE_WEBSITE_BUILD_NEXT }}
            ${{ env.FILE_PATH_UI_BUILD }}
          key: ${{ env.CACHE_KEY_BUILD }}

      - uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: ${{ env.FILE_PATH_UI_BUILD }}
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_STAGE_UI }}

  deploy-ui-prod:
    name: Deploy UI Prod üöÄ
    # needs: [build, lint, tsc, test]
    needs: build
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'

    environment:
      name: UI Prod
      url: https://turbo-ui-prod.netlify.app

    steps:
      - uses: actions/cache@v3
        with:
          path: |
            ${{ env.FILE_PATH_BOILERPLATE_APP_BUILD_NEXT }}
            ${{ env.FILE_PATH_BOILERPLATE_WEBSITE_BUILD_NEXT }}
            ${{ env.FILE_PATH_UI_BUILD }}
          key: ${{ env.CACHE_KEY_BUILD }}

      - uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: ${{ env.FILE_PATH_UI_BUILD }}
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_PROD_UI }}